export { default as Button } from './button/index.vue'
export { openDialog } from './dialog/dialog'
export { default as Dialog } from './dialog/index.vue'
export { default as Switch } from './switch/index.vue'
export { default as Tab } from './tab/index.vue'
export { default as Tabs } from './tabs/index.vue'
export { default as Transfer } from './transfer/index.vue'
